### ISSUE TITLE
First execution of `wyng send`: "No new data"

### ISSUE THREAD

**Issue by gasull** [tasket/wyng-backup#127]
```
$ sudo ./wyng send --verbose
Wyng 0.4.0alpha2 release 20220903
Enter passphrase: 
Encrypted archive last updated 2022-11-02 02:13:21.394775 (+00:00)

Dest location: qubes://admin-backups/media/backups/wyng/
Preparing snapshots...
Warning: Local 'personal' does not exist!
Warning: Local 'shopping' does not exist!
Warning: Local 'untrusted' does not exist!
Warning: Local 'work' does not exist!
No new data.
```

**Comment by tasket** [comment]
@gasull Ah, you're probably not going to like this...  Wyng does not recognize VMs as storage objects, only for facilitating access via a URL like 'qubes://vmname'.  You will need to specify volume names like 'vm-personal-private', 'vm-shopping-private', etc. (Wyng remembers the volume group/pool, so only the volume name is needed when you add volumes).

**Comment by gasull** [comment]
> you're probably not going to like this... Wyng does not recognize VMs as storage objects

I think usability would be much better if VM names could be used.  I see several volume names per VM, and I'm not sure which ones I need to back up.  All of them?  I guess this requires knowing how Xen handles VM storage.

**Comment by tlaurion** [comment]
@gasull qubes storage has two main volumes
- private: your appvm content (/home mainly)
- root: standalonevm/templates. The OS layer

Other volumes types exist:
- volatile: live overlay. This is what permits you to install applications in appvms that won't persist over reboot. This is not really pertinent to backup
- back: qubes revert snapshots

Since wyng is aimed to be OS agnostic, it currently requires from the user to know some OS storagr backend strategies. 

@tasket I agree this should at least be part of the documentation if no helper scripts are planned, to at least point to Qubes documentation, where even official docs should maybe be more explicit about them https://www.qubes-os.org/doc/templates/#inheritance-and-persistence

**Comment by tasket** [comment]
@gasull @tlaurion I created a new [project](https://github.com/tasket/wyng-util-qubes/issues/1) to handle backups at the qvm level.  Its a wrapper for Wyng and it uses qube names instead of volume names.

It does (currently) require that an archive was already created directly with `wyng arch-init -n default` (although `-n default` can be set for an archive later at any point).
