### ISSUE TITLE
Thin Provisioning Tools v1.0 seems to break Wyng

### ISSUE THREAD

**Issue by gdiShun** [tasket/wyng-backup#134]
Specifically, after upgrading from v0.9 to v1.0, `thin_delta` fails with a `Device or resource busy` error, which then causes Wyng's `grep` command to fail out. Downgrading from v1.0 to v0.9, and rebooting, fixed the issue for me. I noticed that running the same `thin_delta` command via terminal will cause a very similar issue in v0.9, but it appears to still go through fine in Wyng, while it does not with v1.0.

https://github.com/jthornber/thin-provisioning-tools

Using Wyng 0.3.3 release 20220829. Did not see any major changes in newer versions to bother trying them yet.

**Comment by tasket** [comment]
@gdiShun Thanks for the report.

The newer Wyng versions have the same LVM code, so I wouldn't expect them to work either.  The TPT page shows v0.9 as the current master, although they have a V1.0.0 tagged, so I guess maybe this is a full release.

This is a little worrying because Wyng already goes out of its way to make sure the pool metadata is un-reserved before attempting to reserve and use it.

BTW if you could include your distro version and kernel version that would help.

**Comment by gdiShun** [comment]
Thanks for the fast response.

Using Arch with 6.1.9 kernel. Tried both Arch's Zen and Standard kernel versions. Also tried LVM2 v2.03.18-1 and v2.03.18-4 before getting to reverting Thin Provisioning Tools. This might not be a problem for distros with normal release schedules for a while though.

**Comment by gdiShun** [comment]
As of v1.0.2-1, it seems the issues have been fixed. Closing this now. Sorry for creating this way too early. :sweat_smile:
