### ISSUE TITLE
Use BTRFS_IOC_TREE_SEARCH_2 instead of FIEMAP on BTRFS

### ISSUE THREAD

**Issue by DemiMarie** [tasket/wyng-backup#162]
Due to how BTRFS works internally, FIEMAP is ill-suited to it.  BTRFS_IOC_TREE_SEARCH_2 should be used instead.

This will likely require calling the ioctl from Python or C, possibly using CFFI.

**Comment by tasket** [comment]
@DemiMarie 

Btrfs is "an extent-based filesystem", from the kernel.org pages.  Data files don't exist without extent representation, and FIEMAP is a list of a file's extents.

The matter comes down to:

1. There is nothing in Btrfs code or structures, that I have seen, showing that FIEMAP omits data.  Suggesting it does is claiming undocumented behavior (in fact, not even documented as bug reports, because there are no relevant ones for this advertised feature that is 9 years old).  The docs have exactly one warning about FIEMAP:  When tools like `filefrag` report values as _physical_, don't believe it...
2. Wyng only needs _logical_ extent info, which is what Btrfs FIEMAP provides.  Different extents (with different ids) may be created to point to same-or-similar sets of chunks and disk blocks ...__and I think this is where people get confused.__  This shows up as a false-positive and only results in Wyng reading and comparing the associated data to determine if its actually different; it does not threaten data integrity.
3. To reinforce no. 2, FIEMAP output is actually quite cautious, reporting extents that are no longer part of a file as flagged for deletion.
4. Btrfs keeps a master transaction indicator for each (sub)volume's Btrees; nothing inside the volume changes without the Btree transaction id also changing.  That's how we know the extent info between two files is consistent, despite the possibility of background maintenance activity.  Wyng's creation of a temporary read-only subvolume + checking its transaction id (before and after) gets the job done.

I've been intensively testing Wyng's FIEMAP access without incident on multi-device Btrfs filesystems.  Apart from perceptions, there are no problems as far as I'm concerned, so reported issues about any shortcomings in FIEMAP will have to be specific and not alluding to "because of things inside".

**Comment by DemiMarie** [comment]
@tasket: See [this linux-btrfs mailing list post](https://lore.kernel.org/linux-btrfs/20210130010329.GB32440@hungrycats.org/).  In short, FIEMAP is both inaccurate and _extremely_ slow on BTRFS.  TREE_SEARCH_V2 is what is recommended by the BTRFS developers.

**Comment by tasket** [comment]
First, I'm not seeing any notable performance issues.  Recent kernels have Btrfs [optimizations for FIEMAP](https://lwn.net/Articles/906802/), but it could also be that the poster's testing regime is a bit extreme.

FIEMAP is a subset of the information contained in the filesystem.  Nevertheless, it still describes file contents from byte 0 through to the end with uniquely identifiable info.

And so far I've seen no explanation of how its inaccurate or otherwise inadequate for differencing two files.  There's been no incident report, either.

But I have a thread about analyzing fragmentation of physical disk blocks, which has nothing to do with Wyng...

> 1.  On btrfs, physical extents and logical extent references have separate
offsets and sizes.  FIEMAP provides for only one size and offset in struct
fiemap_extent, so the btrfs version discards the physical size information
and adds the physical offset to the physical extent's base address.

Yet this is all that's needed here.  If two files each reference the same _logical_ extent, but their extent map entries show different offsets, the ioctl entry from each _still_ would not match—so no false negative.

Logical extent info is all that's needed for this use case.
