### ISSUE TITLE
Support metadata payload for VM config/other

### ISSUE THREAD

**Issue by tasket** [tasket/wyng-backup#18]
Backup and restore additional metadata that the user or host system associates with each volume. For example, VM or container configurations.

This could require additional packaging / un-packaging steps before or after the `send` or `receive` operation runs.

**Comment by tasket** [comment]
There is a workaround for VM metadata which is to `qvm-copy` the /var/lib/qubes/qubes.xml file to a trusted VM (such as vault) before starting the backup. On restore, the xml file can be taken from the vault.

In the long term, some integration with `qvm-backup` may also be in the cards.

**Comment by tlaurion** [comment]
@tasket : what are the challenges here?

**Comment by tasket** [comment]
There is no convenient interface in Qubes for extracting and importing individual VM configurations.

Looking at the way `qvm-backup-restore` does it makes me wonder if it would be better to add a Qubes integration to Wyng for this, or vice-versa (have a qvm-backup mode that uses Wyng for data).

If Wyng is to handle VM configs, I'd prefer some ability in `qvm-create` or `qvm-prefs` to import the listing from `qvm-prefs` or maybe from qubes.xml. OTOH, it may be possible to use python xml libraries to sort of copy-paste a VM's config. Lots to think about.

**Comment by tlaurion** [comment]
@marmarek?

**Comment by marmarek** [comment]
You may want to look at qvm-backup-restore part: https://github.com/QubesOS/qubes-core-admin-client/blob/master/qubesadmin/backup/restore.py#L1942-L2089
This is a complete list of metadata held in qubes.xml for a given VM. In short, it is:
 - properties (qvm-prefs)
 - tags (qvm-tags)
 - features (qvm-features)
 - devices (qvm-device)
 - storage volumes (qvm-volume) - basically what volumes are in which pool (qvm-backup-restore currently does not preserve this)

Restoring some properties and devices may depend on other VMs being restored first (for example netvm restored before pointing other vm's netvm at it) - that's why this code is such long.

As for a _backup_ solution, I think it's safer to include full qubes.xml and process it on restore, than using some intermediate format. This way, in case of any metadata-processing bug, the backup image will most likely be fine and after fixing restore code you can recover your (meta)data. If a bug would be in backup-making code, the risk of (meta)data loss is greater.

I'd really like to have wyng integrated with qvm-backup (one way or another), but I consider data integrity/confidentiality protection (#7 ) a prerequisite.

**Comment by tlaurion** [comment]
@tasket :

Small ongoing PoC trace...

Export:
```
TemplateVMs=$(qvm-ls | grep TemplateVM| awk -F ' ' {'print $1'}); mkdir -p templates; echo "$TemplateVMs"|while read template; do qvm-prefs $template > templates/$template.prefs; qvm-service $template > templates/$template.service; qvm-features $template > templates/$template.features; qvm-tags $template > templates/$template.tags;done; qvm-volume > templates/templates.volume

AppVMs=$(qvm-ls | grep AppVM| awk -F ' ' {'print $1'}); mkdir -p appvms; echo "$AppVMs"|while read appvm; do qvm-prefs $appvm > appvms/$appvm.prefs; qvm-service $appvm > appvms/$appvm.service; qvm-features $appvm > appvms/$appvm.features;qvm-tags $appvm > appvms/$appvm.tags; done; qvm-volume > appvms/appvms.volume
```

**Comment by tlaurion** [comment]
@tasket That would still be lovely.

**Comment by tasket** [comment]
Initial implementation will be via a specially-named logical volume, which will be backed-up normally with the other (user-configured) volumes. A script for this is taking shape under the misc/ folder.

**Comment by tlaurion** [comment]
@tasket I have quickly reviewed the [qubes xml resostore tool implementation](https://github.com/tasket/wyng-backup/blob/7e4012909bfc770c00dc83b74b72d5b192212d91/misc/qubes-wyng-util).

As current implementation:

1- A user would not be able to simply restore one backuped, not existing AppVM/TemplateVM without overwriting the whole qubes.xml QubesOS config. The scope seems to solely restore a whole system from backup; not properties linked to a AppVM/TemplateVM of the XML itself matching VM name. Let's say I deleted my Windows StandaloneAppVM a while ago and now want to restore that VM only; I would not be able to simply restore that root volume + XML attributes; I would need to restore the whole backup of the system.
2- Restoring a system LVMs would imply that other LVMs (AppVMs and Templates) that were previously existing but were not part of that restored backup would be rendered invalid, since the whole XML would be restored. Consequently, there would be LVMs existings on the system, being unlinked from QubesOS manager.

My understanding here is that once encryption is implemented, wyng-backups could be used as a backend/alternative backend for QubesOS backup/restore, taking advantage of the actual [code](https://github.com/QubesOS/qubes-core-admin-client/blob/93608658a9cb6b75fd73168f4fefcc909eb41b09/qubesadmin/backup/restore.py#L2059-L2100) referred by @marmarek that is actually dealing with the [properties, tags, features, devices and storage volumes](https://github.com/tasket/wyng-backup/issues/18#issuecomment-596735184).

But the problem that stays is being able to restore a AppVM/TemplateVM that is not present on the actual system, while not overriding the complete XML file. _But a nice whole restoration tool_. If the goal is to be able to restore from outside of QubesOS, then the current implementation would do (where hardcoded paths won't :) ).

**Comment by tasket** [comment]
@tlaurion 

> 1- A user would not be able to simply restore one backuped, not existing AppVM/TemplateVM without overwriting the whole qubes.xml QubesOS config. 

Although it starts with a routine to save the entire qubes.xml, the recovery routine operates on a per-VM basis. The XML for both the working and backup xml file is parsed so that the VM "domain" can be matched in both copies and then replaced in the working copy.

This method is a quicker (even more generic) way to  do it; IIRC the mentioned properties are contained within the xml. It could later be expanded to use the qubesadmin interface directly and operate like Marek's code. However, I probably wouldn't be willing to throw exceptions in the same places, as the user's main interest is in accessing their restored data; I want to avoid the frustrations that users report with `qubes-backup-restore`.

**Comment by tlaurion** [comment]
@tasket So if I understand well the use case scenario of this, the [qubes-wyng-util script](https://github.com/tasket/wyng-backup/blob/f0d6a7c298bbba5c40f5c6937d1467da2309384f/misc/qubes-wyng-util)
- Needs to be called prior of a send session with meta-prep
- will send another xfs LVM needs to be added to current LVM tracked by wyng
- only works if /var/lib/wyng.backup is the current mata-dir (non configurable).

Questions:

1. Is there any plan to make wyng use this script when qubesos deployment is detected?
2. Passing current meta-dir automatically instead of having it bound to a static meta-dir?
3. Have /boot content + bootblock backuped similarly so that a rootfs can be restored + merged on next reboot while backuped and matching /boot could be restored?

We would then have a working backup/restoration of qubes + rootfs + boot.

**Comment by tasket** [comment]
See commits 0163762, 16a54b4, 5eb0f3c for implementation.

Note this does _not_ use the Qubes API to restore VM settings. You may know that I already have a VM settings modification script called `findpref`, which uses the Qubes API. However, my experience in using it shows going through the API is unreliable (Qubes sometimes complains that a pref is inaccessible, with no underlying reason), and that is not even considering the frustrating contortions that are imposed by the usual Qubes restore process.

An example scenario for an inaccessible pref error is when I change 'netvm' property on some VMs. This occurs even when I've taken care to shutdown all referenced VMs... in fact it also happens when all VMs are shutdown. Allowing this to occur in `qubes-wyng-util` would result in partially-restored settings, which I find totally unacceptable (whether or not an exception is thrown).

Therefore, `qubes-wyng-util` takes a cut-and-paste approach in editing _qubes.xml_; if a VM by the same name already exists in the system, its xml segment is removed completely before being replaced with the backup segment. It regards the VM names as the canonical reference points and adjusts _qid_ properties as needed, and it makes basic checks for VM type and whether templatevm/netvm references already exist. With this method, VMs can also be reliably kept offline the entire time settings are restored, which is another plus.

Finally, it clears the restored VM's dir under /var/lib/qubes and then copies the relevant restored files (usually _firewall.xml_).

This is being offered as a _companion utility_ to Wyng and it requires some coordination from users or a wrapper app. My suggestion for supporting a Qubes full-system restore with Wyng is to backup the partition table with `sfdisk` to /boot, then `rsync` update /boot into a subdir of '/' root or its own separate LV (which has been added to the Wyng volume set).  I'll leave it to the reader to decide if restoring this info correctly is a daunting task.

**Comment by marmarek** [comment]
> Therefore, `qubes-wyng-util` takes a cut-and-paste approach in editing _qubes.xml_;

This sounds like a great way to end up not with just one particular VM partially restored, but with the whole system unbootable... There are serveral things that can go wrong with this approach, like not noticing network cycle, placing AppVM's root volume in a different pool than its template (or, doing the same with a template of already existing AppVMs).

I understand your frustration when some change is refused, but the proper approach here is rather log an error what change was refused, instead of forcibly applying it anyway behind `qubesd` backs, likely bypassing some safety check...

**Comment by tasket** [comment]
> This sounds like a great way to end up not with just one particular VM partially restored, but with the whole system unbootable... There are serveral things that can go wrong with this approach, like not noticing network cycle, placing AppVM's root volume in a different pool than its template (or, doing the same with a template of already existing AppVMs).

Thanks for the heads up @marmarek. I'll mark the code as strictly experimental. But I have to wonder if it isn't better to add checks to handle those conditions?

> I understand your frustration when some change is refused, but the proper approach here is rather log an error what change was refused, instead of forcibly applying it anyway behind qubesd back, likely bypassing some safety check...

My issue with logging / halting w error is that a user is still left with a possibly functioning VM that has the wrong combination of settings. That is a security issue.

In my mind, I would have expected _qubesd_ to continue functioning even if some VM was rendered defunct by the cut/paste restore method.

**Comment by marmarek** [comment]
> My issue with logging / halting w error is that a user is still left with a possibly functioning VM that has the wrong combination of settings. That is a security issue.

Maybe mark the VM as incomplete to prevent it starting? In fact, `qvm-backup-restore --paranoid-mode` in R4.1 uses similar approach: it adds a tag `backup-restore-in-progress`, and then an extension in core-admin prevents such VM from being started.

> In my mind, I would have expected _qubesd_ to continue functioning even if some VM was rendered defunct by the cut/paste restore method.

Manual `qubes.xml` modification is not supported. There is no guarantee what could possibly explode if you do it. For example there is no way qubesd will recover if you make a syntax error there (an extreme example, which isn't the case here, but you get the point).
