### ISSUE TITLE
Working plan to have better qubesos btrfs settings from install

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-backup#211]
Mounted btrfs from tails without specifying mount options got laptop work all night fixing btrfs partition and still undone when waking up this morning.

Will edit post with current applied overrides, but from my understanding, for btrfs to be usable under qubesos in combination of wyng and beesd, a couple of things would need to be done at I stalker level to reduce friction since wyng cannot be used directly on top of fresh install

- /var/lib/qubes needs to be subvolume of rootfs, cannot be seperated btrfs volume otherwise wyng fails doing snapshot of whole varlibqubes subvol (needs to be /var/lib/tmp something something). Wyng script not sufficient. 

- btrfs settings at fs creation needs tweaking. 
- fstab needs tweaking
- QubesOS main volume revert policy needs to be set to 0, monitor needs to be authentication-less to be scheduled as cron job
- luks base container needs to be tweaked for 4k
- data/Metadata needs to be set at single to be compatible with beesd
- btrfs compression needs to be set to off
- from personal experience, not having bees run right after fs creation time takes forever to dedup qubes disk images, even in scan mode 3.

... Plus some other things that are probably slipping from my mind. Of course, bees is out of scope now, but testing btrfs+wyng+bees is way too time consuming and risky without setting default install with proper defaults today. 

Qos 4.2.2rc1 being out, I think it's time to define proper btrfs requirements for fs creation time options. 

Related https://github.com/Zygo/bees/issues/283

**Comment by tasket** [comment]
I would like to expand on this in the near future because I think Btrfs parameters can help performance on systems with very large volumes.  However, maybe want to de-emphasize the install-time aspect, as Qubes can be very nicely configured with Btrfs after install pretty much any time the user desires as long as they have the free space to add a Btrfs volume.

So the critical install-time instruction should begin with "leave most of your space free if you want to setup your VMs on Btrfs from the comfort of your regular dom0 shell" or something to that effect.

**Comment by tasket** [comment]
We might want to try writing a Btrfs setup script which creates its own LUKS container (instruct the user to enter the same pw as for the root system, if they want it to come online immediately) in addition to desired Btrfs formatting options.

**Comment by tlaurion** [comment]
Maybe this discussion should be merged to https://github.com/QubesOS/qubes-issues/issues/6476
