### ISSUE TITLE
A question about receive

### ISSUE THREAD

**Issue by alvinstarr** [tasket/wyng-backup#214]
if I specify a session with receive it appears that all the data up to and including the session are restored.
Which makes sense as a general restore tool.
The documentation kind of implies that if you specify a session only the data with that session will be restored.
Which in our case could be handy.
We have a full restore that takes 30 days to recover.
Because the file system is still in use we would like to be able to take a snapshot later and then apply only that snapshot to the previously restored data.
The snapshot should have a size measured in GB where the full backup has a size measured in TB so it should be much faster to apply.

**Comment by tasket** [comment]
Only one version (session) of a volume will be restored, but since Wyng is incremental it will draw on some data from earlier sessions as necessary to create a complete volume.  It does not read all of the data from earlier sessions (unless you had only two sessions total and the newest one had zero changes vs the first).

A _session_ can be thought of as references to _all_ the data present in the volume at the specified point in time... or as being only the _differences_ between it and the prior session.  In terms of storage in the archive, its the latter but during `receive` Wyng has to construct a bit-perfect representation via the former.

The implication in the doc is correct, however:  That earlier data may retrieved in certain places because it was _also_ present in the volume when the requested session was created (e.g. those places hadn't changed).  But the retrieval could be either from the archive _or_ from local storage (see below).

> We have a full restore that takes 30 days to recover.
> Because the file system is still in use we would like to be able to take a snapshot later and then apply only that snapshot to the previously restored data.
The snapshot should have a size measured in GB where the full backup has a size measured in TB so it should be much faster to apply.

I don't know if I fully understand this, but it seems like you want to restore data as efficiently as possible, resulting in different versions on your local disk that only consume space (and restore time) according to the differences between those snapshots. If that is what you had in mind, then Wyng can do it when using either `--use-snapshot` or `--sparse` options.

OTOH, applying un-archived updates to a local snapshot that had been restored from an archive is a different proposition.  In that case it could make more sense to simply replace the older local volume with a snapshot of the updated volume.  As long as you're not doing a plain copy (i.e. a proper snapshot or reflink function is used) then shared extents between the snapshots will remain that way and speed + space should be close to optimal. (Note that if you're using Thin LVM, Btrfs, XFS then the old logistics of updating "thick" LVM snapshots do not apply).

**Comment by alvinstarr** [comment]
Let me try and explain a full timeline and hopefully it will make sense.
The timelines below are a bit arbitrary but not all that far off how long things take.

- day1:  I start a full backup
- day 5: the backup finishes.
- day 6: copy the backup to a remote site
- day 8: the copy is complete.
- day 9: start a restore(receive)
- day 49: the restore is complete.

At this point I have a 49 day old backup image.

If I take a snapshot at this point it will run in a day.

- day 50: start snapshot
- day 51 snapshot completes
- day 52 copy snapshot to remote site.
- day 53 start restore.
 
now here is the problem if I restore the volume using the snapshot and it tries to recover all the previous data then it will take me another 40 days.
but restoring just the data in the snapshot will  only take a day or so.
This will work so long as the first restore has not ever been mounted or changed.

It is really a weird corner case caused by the massive size of the volumes to start with.
The individual snapshots are tiny  because the volumes do not have a lot of change.

**Comment by tasket** [comment]
OK, that is a fairly simple scenario, apart from the long delays. The solution is similar to my last reply, which is to receive with `--use-snapshot` (and add `--sparse` for good measure, it will fall back to sparse if a Wyng local snapshot isn't present).  If the Wyng local snapshot for that volume is present, then `--use-snapshot` will do its magic: it will not only retrieve the bare minimum from the archive, but it will also instantly know what that minimum is.  If there is no Wyng local snapshot, then it will go into sparse mode and read each chunk of the local volume to determine what it must fetch from the archive to restore the volume.

Also, if there is neither a local volume/snapshot nor a Wyng local snapshot at the expected local path, then `wyng receive` will have to retrieve the entire volume from the archive (e.g. if the session being received was for a 1TB volume that was half full, in that case it will have to transfer 500GB).

Clarification:  I'm using _"snapshot"_ to mean a version of a local volume, and _"session"_ to mean a version of a volume in the archive.
