### ISSUE TITLE
No space in LVM pool on VM restore

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-backup#55]
Recreated build-x230-flash-coreboot-48 from QubesOS.
```

[user@dom0 ~]$ time sudo wyng-backup-master/wyng list|grep flash
   58.8 GB  vm-build-x230-flash-coreboot-48-private

real	0m0.450s
user	0m0.194s
sys	0m0.210s

```

Before restore:
```
[user@dom0 ~]$ sudo lvs
  LV                                                 VG         Attr       LSize   Pool   Origin                                             Data%  Meta%  Move Log Cpy%Sync Convert
  pool00                                             qubes_dom0 twi-aotz-- 177.48g                                                           62.83  47.12                           
  root                                               qubes_dom0 Vwi-aotz-- 177.48g pool00                                                    4.88                                   
  root.tick                                          qubes_dom0 Vri-a-tz-- 177.48g pool00 root                                               4.87                                   
  swap                                               qubes_dom0 -wi-ao----   7.66g                     

```

```
[user@dom0 ~]$ time sudo wyng-backup-master/wyng receive vm-build-x230-flash-coreboot-48-private --save-to=/dev/mapper/qubes_dom0-vm--build--x230--flash--coreboot--48--private 

!! This will erase all existing data in /dev/mapper/qubes_dom0-vm--build--x230--flash--coreboot--48--private !!
   Are you sure? [y/N]: y

Reading manifests..
Checking metadata..
Saving to /dev/mapper/qubes_dom0-vm--build--x230--flash--coreboot--48--private

Receiving volume vm-build-x230-flash-coreboot-48-private S_20200207-215037
Traceback (most recent call last):
  File "wyng-backup-master/wyng", line 2418, in <module>
    save_path=options.saveto)
  File "wyng-backup-master/wyng", line 2088, in receive_volume
    savef.write(buf)
OSError: [Errno 28] No space left on device

real	0m51.957s
user	0m21.071s
sys	0m5.714s

```
After failed restore:
```
[user@dom0 ~]$ sudo lvs
  LV                                                 VG         Attr       LSize   Pool   Origin                                             Data%  Meta%  Move Log Cpy%Sync Convert
  pool00                                             qubes_dom0 twi-aotz-- 177.48g                                                           63.79  47.22                           
  root                                               qubes_dom0 Vwi-aotz-- 177.48g pool00                                                    4.88                                   
  root.tick                                          qubes_dom0 Vri-a-tz-- 177.48g pool00 root                                               4.87                                   
  swap                                               qubes_dom0 -wi-ao----   7.66g                
```

qvm-remove build-x230-flash-coreboot-48 gives same lvs output of first output.

Simply not enough LVM pool space?

**Comment by tasket** [comment]
@tlaurion I'm surprised wyng started, since it usually barfs if dashed options appear after the command. But that's not the issue. And probably not space, if your volume contents are about 65GB or less (if the pool overall has 37% free).

The line where wyng detects the vg (thin LV save mode) is this:
```
if vg_exists(os.path.dirname(save_path)):
```
The volume group has to look like its own dir under /dev, which now seems to be the preferred mode for accessing them (lvm lists paths this way, not the mapper way). The way you specified it, wyng probably tried to create a non-LV volume.

Try it with:
```
--save-to=/dev/qubes_dom0/vm-build-x230-flash-coreboot-48-private
```
---

There is probably some way I can make this nicer, such as doing away with the path altogether (user must specify --local=vg/pool then lv name) or something else. Problem here is /dev/mapper doesn't really delineate vg names, so it becomes a guessing game about what's LVM and non-LVM, especially if the save path doesn't already exist. If it exists, you can run lvdisplay on the path to see if it returns an error, but that's a big 'if'.

What I may do in this case is display an error if a /dev/mapper path doesn't already exist, and suggest the user try '/dev/vgname' if they really want to save to the vg/pool.

**Comment by tlaurion** [comment]
Good catch but the volume already existed. My problem was the the volume was fixed to be 2gb from qubesos AppVM creation. Extending it inside of qubesos fixed my problem.

Can't wait for qubesos artifact to be exported reinjected so an appvm can be backuped and restored magically.

**Comment by tasket** [comment]
Hmmm, that volname wasn't shown in your lvs output.

I think my analysis is correct here, since wyng assumes that a non-LV block device is static, e.g. it doesn't try to resize it. It also doesn't re-create your deltamap and .tick volume in that case.

If you use the /dev/vgname path, it will resize the volume before saving. If the volname is also the same, it will then create a .tick snapshot and an empty deltamap (and suggest that you run `--remap diff` as well).

**Comment by tlaurion** [comment]
Yep i think your analysis is right and I used /dev/mapper/volume path (which are linked to DM volumes there) but since autocompletion provided me the right volume name corresponding to the volume I wanted to restore, I selected that instead of /dev/qubes_dom0/vm-name-private path.

Will restore next volume directly there tomorrow morning, without using QubesOS to resize volume first and see if everything works as expected. I seem to have chosen badly /dev/mapper/ path instead of vol/pool by not knowing better.

**Comment by tlaurion** [comment]
lvs output was truncated but volume was there, pointing to the right dm-linked device.

**Comment by tlaurion** [comment]
Thanks! Will reopen if needed!

**Comment by tasket** [comment]
BTW, this change should handle /dev/mapper now when the volume already exists. Otherwise, will exit with a suggestion.
