### ISSUE TITLE
Snapshotting /dev/sda1 (boot) into LVM thin pool

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-backup#63]
Hey, was wondering if there was a more elegant way then [this](https://unix.stackexchange.com/questions/35286/how-to-create-a-snapshot-of-a-physical-disk) that could also be accomplished on [shutdown](https://github.com/QubesOS/qubes-issues/issues/5094#issuecomment-502077678) to snapshot /boot to be backuped by wyng? 

How would you adapt this?
```
lvcreate -n store -L 10g vg
echo 0 `blockdev --getsz /dev/sda1` snapshot-origin /dev/sda1 | dmsetup create origin
echo 0 `blockdev --getsz /dev/sda1` snapshot /dev/mapper/origin /dev/mapper/vg-store N 128 | dmsetup create snap
```
Doing one last clone of disk prior of trying to figure this out.

**Comment by tlaurion** [comment]
Seems like syntax is not right. Getting my head around https://wiki.gentoo.org/wiki/Device-mapper#Creating_snapshots

**Comment by tlaurion** [comment]
@tasket 

So what I try to accomplish seems similar to [this](https://wiki.gentoo.org/wiki/Device-mapper#Creating_external_thin_snaphot). 

Unfortunately, my dmsetup and LVM fu is limited and I can't figure out how to get that thin volume created (what is that 438 value?) :
```
dmsetup message /dev/mapper/test-thin-pool 0 "create_thin 438"
dmsetup create test-thin-extsnap --table '0 390625 thin /dev/mapper/test-thin-pool 438 /dev/loop1'
```
where the --table value can be crafted from :
`echo 0 `blockdev --getsz /dev/sda1``

The DM symlink saw on /dev/qubes_dom0/X -> /dev/mapper/Y ?)

**Comment by tasket** [comment]
Initial response (I could be wrong) is this approach doesn't work bc the thin volume is only acting as a backing store for the dm virtual device, and only changed chunks go into the thin volume. However, is you manage that thin volume as a permanent 'partner' to /boot partition, maybe it could work.

But fundamental issue still exists (why Wyng hinges on the concept of dedicated CoW storage like LVM or Btrfs) which is that /boot is itself not CoW and may be accessed/written independently of whatever dm layer you are employing. This opens the scheme to data corruption issues.

I'll spend some time tonight looking into it further.

**Comment by tasket** [comment]
BTW, when Gentoo doc says "ordinal" such as 438, I believe this refers to thin-lvm's own volume numbering scheme which you can view with `lvs -o lv_name,thin_id`. You can probably just use `lvcreate` to make a thin volume, fetch the thin_id with `lvs` and then feed that id into the second command `dmsetup create` in your example. Its more steps, but you don't have to find an unallocated number that way.

**Comment by tlaurion** [comment]
@tasket any insight in making the thin volume a permanent partner of physical volume? 

Goal would be to have a shutdown snapshot, and be able to receive/verify and save it back to original partition.

**Comment by tasket** [comment]
I haven't found any way to permanently pair an lvm snapshot with a simple block device. The requirement that source volumes must reside in lvm is the enabling detail that means volume changes are always tracked by the OS – regardless of the circumstances. So I am wary of trying to shoehorn a CoW emulation using active measures because the guarantee of CoW constancy goes way down in that case.

---

However, it looks like issue #70 implementation could open several doors and this would be one of them... Non-lvm volumes could be added directly to archive config, and the (new) remapper would simply kick in for each and every `send` so that only changes are sent; This would be the trade-off for being able to add non-CoW volumes. Speed wise, it should be far better than what you see from the current remapper because its CPU-bound not net-bound.

Essentially, what results with the above is that you get conventional backup performance for non-lvm volumes, since Wyng is then doing the same work as a regular always-rescanning backup tool.

An alternative to this would be making this process disk-bound, i.e. performing a copy into a snapshot which consumes both disk IO and extra space.

**Comment by tasket** [comment]
See comments in issue #31
