### ISSUE TITLE
Is it safe to delete qube and restore it using qube clone?

### ISSUE THREAD

**Issue by gangamstyle** [tasket/wyng-backup#74]
Thank you! Your backup tool is awesome! Very fast and efficient, I love it!

Let me ask, what will happen if I:

1. create a backup of qube vm (named Dummy) using wyng
2. clone Dummy to Dummy-clone using qube manager
3. use Dummy for some time
4. make wyng backup of Dummy again
5. decide to rollback, delete original Dummy and restore it from Dummy-clone by cloning Dummy-clone to clone named Dummy (x100 times faster)
6. start wyng backup on Dummy again, without removing old backup(s)

Will wyng fail?

**Comment by tasket** [comment]
Thanks!

IIRC, I may have done this once or twice myself. The steps you describe should cause Wyng (at step 6) to process a larger number of changes than would otherwise be necessary, and that one backup session will go more slowly. More CPU will be used for extra comparisons, and slightly more disk space used on the destination unless you were making a ton of changes to Dummy. Or you can keep the added disk usage to a bare minimum in this case by using `--testing-dedup=5` to turn on deduplication for that one backup session.

The reason this should work is that the only 'error' introduced here would possibly be LVM reporting a larger than normal set of changes between the volumes, and Wyng will parse through them and decide what has actually changed.

If you would like verification this has worked correctly, then after step 6 perform a `wyng diff volumename` which will compare the archive volume with the local volume bit by bit.

Also note in your example, the LVs for the two VMs are still related via LVM's snapshot mechanism. But this isn't really necessary, and even if you replaced Dummy with a VM volume that was copied without the benefit of snapshotting then LVM would tell Wyng the entire volume was changed and Wyng would do its slow comparisons on the entire volume during 'send', behaving like a traditional incremental backup for that one session.

**Comment by tasket** [comment]
Another note:

The past changes in Dummy will still be a part of the archive's backup history. You could, for instance, recover that info you backed up earlier in step 4. You could also decide to remove that history by using the `prune` feature after step 6.

**Comment by gangamstyle** [comment]
Backup created, wyng diff finished with success.
Awesome!
Thank you!
