### ISSUE TITLE
Shallow comparison with borg & restic

### ISSUE THREAD

**Issue by dumblob** [tasket/wyng-backup#92]
Apart from the requirement of LVM (unlike borg & restic), could you somehow compare the features, speed and other (dis)advantages of borg, restic, and wyng?

Btw. I'd like to mention that neither borg nor restic support FEC (forward error correction) to shield against (mainly silent) HW mistakes - does wyng do better on this front?

**Comment by tasket** [comment]
Wyng only has error detection, not correction. I recommend looking for error correction features for your chosen backup storage layer/device, or keeping a duplicate of your Wyng archive – the latter can be done efficiently with `rsync` so that only new/updated chunk files are copied to the duplicate. (Also worth noting that built-in error correction in an isolating+encrypting app creates a substantial attack surface that can be exploited; this is a good reason to use correction on a layer below the archive format.)

Naturally, Wyng can't store files directly; to do that you need to put them in an LV first.

Wyng also doesn't have an encryption-enabled version that is nearing release. V0.4alpha has encryption and basically works but may be 6 mo. or more from beta stage.

### Wyng advantages:

* My limited use of borg shows it to be slower and more network intensive than Wyng on frequently used operations, such as backup and prune. This assumes borg is backing up whole LVs. Much of the difference in speed/efficiency is due to Wyng's use of LVM/CoW metadata, making data re-scanning unnecessary.

* Wyng has a simple format and appears to be less 'interactive' with its archive data, which has both speed and security benefits. LVs are stored as many chunk files and the vast majority of Wyng remote operations are _put file_, _mv_, _rm_, and _ln_. The philosophy is that CoW snapshot storage is becoming common on local systems, while POSIX filesystems are common on remote systems; bridging the features of both enables better performance and security.

* Wyng can safely operate in a network-isolated admin environment (i.e. where an admin storage VM lacks NICs and net routing) where borg cannot strictly do so without moving sensitive code+operations to less trusted / more exposed guest VMs. (Exception to this is attaching a remote disk image locally, which is slower and can jam the admin env.)

As a longtime QubesOS user myself, this isolation-friendly aspect is not accidental; its a critical security feature.

OTOH, if mounting+accessing source LVs is considered OK for your threat model (admin isolation is a non-issue and borg is allowed to process them internally), then Wyng's advantage isn't as clear. But it can still be more efficient if the source data changes between backups are mostly in med-large size files.

* I might be wrong on this one, but it looked to me like borg has a significant number of 'beta' version formats that aren't quite compatible with each other. I've seen users urged to keep upgrading and ditch their existing archives. Wyng only has two format versions, with the latter being the currently evolving alpha; so I would say its relatively stable compared to borg.

**Comment by tlaurion** [comment]
> I might be wrong on this one, but it looked to me like borg has a significant number of 'beta' version formats that aren't quite compatible with each other. I've seen users urged to keep upgrading and ditch their existing archives. Wyng only has two format versions, with the latter being the currently evolving alpha; so I would say its relatively stable compared to borg.

Where format changes are still a thing and should be made somewhat compatible otherwise long term archives are to be dismissed which is a big bump for me testing wyng as before.

**Comment by tasket** [comment]
Only thing I can say to that is the V2 format (Wyng 0.3) won't change, and what comes next should be stable across years as well.  Chances of a quick archive conversion for non-encrypted archives are pretty good.
